name: Main - Build LaTeX PDFs
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Workshops/Workshop1/**.tex'
      - 'Workshops/Workshop2/**.tex'
      - 'Workshops/Workshop3/**.tex'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      # Crear directorios build si no existen
      - name: Create build directories
        run: |
          mkdir -p Workshops/Workshop1/build
          mkdir -p Workshops/Workshop2/build
          mkdir -p Workshops/Workshop3/build
           
      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-basic:latest
          extra_packages: "geometry graphicx hyperref babel amsmath amssymb titlesec enumitem xcolor"
          root_file: |
            Workshops/Workshop1/Workshop1.tex
            Workshops/Workshop2/Workshop2.tex
            Workshops/Workshop3/Workshop3.tex
          compiler: pdflatex
          args: >
            -output-directory=./build
            -interaction=nonstopmode
            -file-line-error
          work_in_root_file_dir: true
          
      # Verificar que los PDFs se crearon correctamente
      - name: Verify PDFs exist
        run: |
          ls -la Workshops/Workshop1/build/
          ls -la Workshops/Workshop2/build/
          ls -la Workshops/Workshop3/build/
       
      - name: Upload Workshop1 PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: workshop1-pdf
          path: Workshops/Workshop1/build/Workshop1.pdf
          if-no-files-found: error
         
      - name: Upload Workshop2 PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: workshop2-pdf
          path: Workshops/Workshop2/build/Workshop2.pdf
          if-no-files-found: error

      - name: Upload Workshop3 PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: workshop3-pdf
          path: Workshops/Workshop3/build/Workshop3.pdf
          if-no-files-found: error